import type { Sop } from './types';

export const SOPS: Sop[] = [
  {
    id: 'write-weekly',
    title: '写周报（15-30min）',
    category: '写作',
    tags: ['工作', '输出', '写作'],
    summary: '快速产出一版可读周报，聚焦成果与影响。',
    estimatedMinutes: 20,
    tutorialUrl: 'https://example.com/guide/weekly-report',
    steps: [
      { id: 's1', title: '列成果要点（3-5条，用动词+影响）', required: true, copyText: '本周关键成果：\n- [动词] [产出/动作]，带来 [影响/指标]\n- [动词] [产出/动作]，带来 [影响/指标]\n- ...' },
      { id: 's2', title: '选结构', type: 'choice', options: ['按项目', '目标/本周/下周/风险'], required: true },
      { id: 's3', title: '充实数据与链接', tip: 'Jira/PR/指标截图，控制信息密度', links: [{ text: 'Jira/PR记录', url: 'https://example.com' }], required: false, copyItems: [ { label: '模板段落', value: '支持材料：链接/截图/指标摘要' } ] },
      { id: 's4', title: '写下周计划与风险', required: true },
      { id: 's5', title: '自检与润色', tip: '删无用细节，突出影响', required: true },
    ],
  },
  {
    id: 'meeting-retro',
    title: '会议复盘（10-20min）',
    category: '会议',
    tags: ['复盘', '沟通'],
    summary: '从事实-感受-改进出发，沉淀可执行改进点。',
    estimatedMinutes: 15,
    tutorialUrl: 'https://example.com/guide/meeting-retro',
    steps: [
      { id: 's1', title: '还原事实（目标/过程/结果）', required: true, copyItems: [ { label: '事实要点框架', value: '目标：\n过程：\n结果：' } ] },
      { id: 's2', title: '记录亮点与不足', required: true },
      { id: 's3', title: '提炼1-3条改进措施', required: true, copyText: '改进建议：\n1. [建议] -> 负责人：[人] 截止：[日期]\n2. [建议] -> 负责人：[人] 截止：[日期]' },
      { id: 's4', title: '确定责任人与跟进时间', required: true },
      { id: 's5', title: '分享复盘纪要', required: false },
    ],
  },
  {
    id: 'pomodoro-focus',
    title: '番茄专注（25+5）',
    category: '专注',
    tags: ['效率', '专注'],
    summary: '一轮25分钟深度工作+5分钟休息，简单可复用。',
    estimatedMinutes: 30,
    steps: [
      { id: 's1', title: '明确本轮目标（可量化）', required: true, copyText: '本轮目标：' },
      { id: 's2', title: '关通知与无关页面', required: true },
      { id: 's3', title: '启动25分钟计时', required: true },
      { id: 's4', title: '记录分心/阻碍（不行动）', required: false },
      { id: 's5', title: '休息5分钟（走动/喝水/拉伸）', required: true },
    ],
  },
  {
    id: 'quick-research',
    title: '快速调研（60-90min）',
    category: '学习',
    tags: ['调研', '学习'],
    summary: '明确问题-收集材料-归纳对比-得出建议。',
    estimatedMinutes: 75,
    tutorialUrl: 'https://example.com/guide/quick-research',
    steps: [
      { id: 's1', title: '明确核心问题与范围', required: true, copyText: '问题：\n范围：\n不在范围：' },
      { id: 's2', title: '搜索与筛选3-5个高质量来源', required: true },
      { id: 's3', title: '要点摘录与结构化记录', required: true, copyItems: [ { label: '摘录框架', value: '来源：\n要点：\n证据：\n疑问：' } ] },
      { id: 's4', title: '横向对比与结论', required: true },
      { id: 's5', title: '输出行动建议与下一步', required: true },
    ],
  },
  {
    id: 'knowledge-card',
    title: '知识卡片（15-30min）',
    category: '写作',
    tags: ['学习', '输出'],
    summary: '把零散笔记固化为结构化卡片，方便复用与分享。',
    estimatedMinutes: 20,
    steps: [
      { id: 's1', title: '选主题与应用场景', required: true },
      { id: 's2', title: '三点式要点（是什么/为什么/怎么做）', required: true },
      { id: 's3', title: '例子或小练习', required: false },
      { id: 's4', title: '相关链接与参考', required: false },
      { id: 's5', title: '复查可读性（删除噪音）', required: true },
    ],
  },
  {
    id: 'weekly-plan',
    title: '周计划（30-45min）',
    category: '规划',
    tags: ['计划', '时间管理'],
    summary: '从目标出发，聚焦关键结果与时间块。',
    estimatedMinutes: 40,
    steps: [
      { id: 's1', title: '回顾上周：完成/未完成/原因', required: true },
      { id: 's2', title: '设定本周3个关键结果', required: true, copyItems: [ { label: 'OKR草案', value: 'KR1：\nKR2：\nKR3：' } ] },
      { id: 's3', title: '时间块安排（日历化）', required: true },
      { id: 's4', title: '识别风险与缓冲', required: false },
      { id: 's5', title: '第一天起手任务', required: true },
    ],
  },
];